name: simple_stomp
description: This is a pure dart Stomp v1.2 client implementation for connecting to a Message Brocker.
version: 0.0.1
repository: https://github.com/flutterings/stomp.dart

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
